---
title: "Download and clean population data"
subtitle: "Sports Facilities in Scotland"
author: "Lesley Duff"
format: html
editor: visual
params:
  filename_population_scotland_csv: "scotland-population.csv"
  filename_population_scotland_raw: "mid-year-pop-est-time-series.xlsx"
  url_population_data_source: "https://www.nrscotland.gov.uk/files//statistics/population-estimates/mid-year-pop-est-time-series.xlsx"
  sheet_population_data: "Table 3"
  sheet_population_skip: 5
---

## Data Source

[Population Estimates Time Series Data](https://www.nrscotland.gov.uk/statistics-and-data/statistics/statistics-by-theme/population/population-estimates/mid-year-population-estimates/population-estimates-time-series-data)

National Records of Scotland

This time series section provides access to the latest time series data, taking into account any revisions or corrections over the years.

All content is available under the [Open Government Licence v3.0](https://www.nationalarchives.gov.uk/doc/open-government-licence/ "Link to Open Government Licence v3.0") except where otherwise stated.

```{r}
library(dplyr)
library(glue)
library(here)
library(janitor)
library(readr)
library(readxl) # For processing Excel spreadsheets
```

```{r}
#| label: download-population-data

path_population_spreadsheet_raw <- here::here("data-raw",
                                              params$filename_population_scotland_raw)

message(glue::glue("Downloading population data from {params$url_population_data_source}"))
# This is provided as an Excel spreadsheet
download_result <- download.file(params$url_population_data_source,
              path_population_spreadsheet_raw, quiet = FALSE,
              mode = "wb")

#  0 for success and non-zero for failure.
download_ok <- download_result == 0

if (!download_ok) {
  print("Error downloading population file")
  stop()
}
```

```{r}
#| label: clean-population-data

# Read the spreadsheet file
population_data_spreadsheet_raw <- readxl::read_xlsx(path_population_spreadsheet_raw,
                                                 sheet = params$sheet_population_data,
                                                 skip = params$sheet_population_skip) |>
  janitor::clean_names()

# Get the sheet out of the spreadsheet
# Mid-year population estimates by administrative area and sex, 1981-2022 [note 1] [note 2]
population_data_spreadsheet <- population_data_spreadsheet_raw |>
  filter(sex == "Persons", area_type == "Country", area_type == "Council area") |>

  # Keep the last column as the 'latest' year of poopulation data available
  select(area_type, area_name = area_name_note_3, last_col())
```


```{r}
#| label: write-population-data
write_csv(population_data_spreadsheet, here::here("data",
                                                  params$filename_population_scotland_csv))
```
